services:

  extraction-api:
    command: uwsgi --chdir ./src --wsgi-file main.py --callable app --http :5000
    healthcheck:
      test: ['CMD-SHELL', 'timeout 5s bash -c ":> /dev/tcp/$${HOSTNAME}/5000"']
      interval: 30s
      timeout: 10s
      retries: 3
    ports:
      - 5000:5000

  extraction-worker:
    command: rq worker --path ./src --url redis://redis:6379/0
    deploy:
      replicas: 24
      resources:
        limits:
          cpus: '1'
          memory: 512m
      placement:
        max_replicas_per_node: 8
        constraints:
          - node.role==worker
    environment:
      http_proxy:
      https_proxy:
      KAFKA_BROKER_URL: broker:29092
    healthcheck:
      test: ['CMD', 'rq', 'info', '--url', 'redis://redis:6379/0']
      interval: 30s
      timeout: 10s
      retries: 3

  text-annotator:
    deploy:
      replicas: 4
      resources:
        limits:
          cpus: '2'
          memory: 4G
      placement:
        max_replicas_per_node: 2
        constraints:
          - node.role==worker
    environment:
      http_proxy:
      https_proxy:
      KAFKA_BROKER_URL: broker:29092
    volumes:
      - annotation-db:/usr/src/app/src/core/data

  text-geocoder:
    deploy:
      replicas: 2
      resources:
        limits:
          cpus: '2'
          memory: 8G
      placement:
        max_replicas_per_node: 1
        constraints:
          - node.role==worker
    environment:
      http_proxy:
      https_proxy:
      KAFKA_BROKER_URL: broker:29092
    volumes:
      - geocode-db:/usr/src/app/src/core/data

  redis:
    environment:
      REDIS_ARGS: --save 60 1000
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 5s
      timeout: 10s
      retries: 10
    volumes:
      - redis-db:/data

  zookeeper:
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_TICK_TIME: 2000
    healthcheck:
      test: ['CMD', 'bash', '-c', "echo 'ruok' | nc localhost 2181"]
      interval: 10s
      timeout: 5s
      retries: 5
    ports:
      - 2181:2181

  broker:
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: 'zookeeper:2181'
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT,PLAINTEXT_HOST:PLAINTEXT
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://broker:29092,PLAINTEXT_HOST://${KAFKA_BROKER_HOST:-localhost}:9092
      KAFKA_METRIC_REPORTERS: io.confluent.metrics.reporter.ConfluentMetricsReporter
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
      KAFKA_GROUP_INITIAL_REBALANCE_DELAY_MS: 0
      KAFKA_CONFLUENT_LICENSE_TOPIC_REPLICATION_FACTOR: 1
      KAFKA_CONFLUENT_BALANCER_TOPIC_REPLICATION_FACTOR: 1
      KAFKA_TRANSACTION_STATE_LOG_MIN_ISR: 1
      KAFKA_TRANSACTION_STATE_LOG_REPLICATION_FACTOR: 1
      KAFKA_JMX_PORT: 9101
      KAFKA_JMX_HOSTNAME: localhost
      KAFKA_CONFLUENT_SCHEMA_REGISTRY_URL: http://schema-registry:8081
      CONFLUENT_METRICS_REPORTER_BOOTSTRAP_SERVERS: broker:29092
      CONFLUENT_METRICS_REPORTER_TOPIC_REPLICAS: 1
      CONFLUENT_METRICS_ENABLE: 'false'
      CONFLUENT_SUPPORT_CUSTOMER_ID: 'anonymous'
    healthcheck:
      test: [ "CMD", "bash", "-c", 'nc -z localhost 9092' ]
      interval: 10s
      timeout: 5s
      retries: 5
    ports:
      - 9092:9092
      - 9101:9101

volumes:
  annotation-db:
    name: annotation-db
  geocode-db:
    name: geocode-db
  redis-db:
    name: redis-db
