services:

  redis:
    environment:
      REDIS_ARGS: --save 60 1000
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 5s
      timeout: 10s
      retries: 10
    image: ${DOCKER_REGISTRY:-index.docker.io}/redis:7.0.5-alpine
    ports:
      - "6379:6379"

  extractors-listener:
    command: --listen
    depends_on:
      - redis
    environment:
      http_proxy:
      https_proxy:
      KAFKA_BROKER_HOST:
    image: ${DOCKER_REGISTRY:-index.docker.io}/pipeline/extractors:0.1.0
    network_mode: host

  extractors-worker:
    command: --worker
    depends_on:
      - redis
    deploy:
      replicas: 8
      resources:
        limits:
          cpus: '2'
          memory: 128m
    environment:
      http_proxy:
      https_proxy:
      KAFKA_BROKER_HOST:
    image: ${DOCKER_REGISTRY:-index.docker.io}/pipeline/extractors:0.1.0
    network_mode: host

  text-annotator-listener:
    command: --listen
    depends_on:
      - redis
    environment:
      http_proxy:
      https_proxy:
      KAFKA_BROKER_HOST:
    image: ${DOCKER_REGISTRY:-index.docker.io}/pipeline/transformers/text-annotator:0.1.0
    network_mode: host
    volumes:
      - annotation-db:/usr/src/app/src/app/data

  #text-annotator-worker:
  #  command: --worker
  #  depends_on:
  #    - redis
  #  deploy:
  #    replicas: 4
  #    resources:
  #      limits:
  #        cpus: '8'
  #        memory: 4G
  #  environment:
  #    http_proxy:
  #    https_proxy:
  #    KAFKA_BROKER_HOST:
  #  image: ${DOCKER_REGISTRY:-index.docker.io}/pipeline/transformers/text-annotator:0.1.0
  #  network_mode: host
  #  volumes:
  #    - annotation-db:/usr/src/app/src/app/data

  text-geocoder-listener:
    command: --listen
    depends_on:
      - redis
    environment:
      http_proxy:
      https_proxy:
      KAFKA_BROKER_HOST:
    image: ${DOCKER_REGISTRY:-index.docker.io}/pipeline/transformers/text-geocoder:0.1.0
    network_mode: host
    volumes:
      - geocode-db:/usr/src/app/src/app/data

  #text-geocoder-worker:
  #  command: --worker
  #  depends_on:
  #    - redis
  #  deploy:
  #    replicas: 4
  #    resources:
  #      limits:
  #        cpus: '8'
  #        memory: 8G
  #  environment:
  #    http_proxy:
  #    https_proxy:
  #    KAFKA_BROKER_HOST:
  #  image: ${DOCKER_REGISTRY:-index.docker.io}/pipeline/transformers/text-geocoder:0.1.0
  #  network_mode: host
  #  volumes:
  #    - geocode-db:/usr/src/app/src/app/data

volumes:
  annotation-db:
    name: annotation-db
  geocode-db:
    name: geocode-db
