services:

  extractors:
    deploy:
      replicas: 8
      resources:
        limits:
          cpus: '1'
          memory: 128m
      placement:
        constraints:
          - node.role==worker

  text-annotator:
    deploy:
      replicas: 4
      resources:
        limits:
          cpus: '2'
          memory: 4G
      placement:
        max_replicas_per_node: 2
        constraints:
          - node.role==worker

  text-geocoder:
    deploy:
      replicas: 2
      resources:
        limits:
          cpus: '2'
          memory: 8G
      placement:
        max_replicas_per_node: 1
        constraints:
          - node.role==worker
