services:

  extractors:
    deploy:
      placement:
        constraints:
          - node.role==worker

  text-annotator:
    deploy:
      placement:
        max_replicas_per_node: 4
        constraints:
          - node.role==worker

  text-geocoder:
    deploy:
      placement:
        max_replicas_per_node: 2
        constraints:
          - node.role==worker
