networks:
  backend:
    name: backend

services:

  extraction-api:
    depends_on:
      - redis
    image: ${DOCKER_REGISTRY:-index.docker.io}/drop/extraction-api:${EXTRACTION_API_RELEASE:-local}
    networks:
      backend:

  extraction-worker:
    depends_on:
      - redis
    image: ${DOCKER_REGISTRY:-index.docker.io}/drop/extraction-api:${EXTRACTION_API_RELEASE:-local}
    networks:
      backend:

  text-annotator:
    image: ${DOCKER_REGISTRY:-index.docker.io}/drop/transformers/text-annotator:${TEXT_ANNOTATOR_RELEASE:-local}
    networks:
      backend:

  text-geocoder:
    image: ${DOCKER_REGISTRY:-index.docker.io}/drop/transformers/text-geocoder:${TEXT_GEOCODER_RELEASE:-local}
    networks:
      backend:
  
  redis:
    image: ${DOCKER_REGISTRY:-index.docker.io}/redis:7.0.5-alpine
    networks:
      backend:

  zookeeper:
    hostname: zookeeper
    image: ${DOCKER_REGISTRY:-index.docker.io}/confluentinc/cp-zookeeper:7.4.0
    networks:
      backend:

  broker:
    depends_on:
      - zookeeper
    hostname: broker
    image: ${DOCKER_REGISTRY:-index.docker.io}/confluentinc/cp-server:7.4.0
    networks:
      backend:

  elasticsearch:
    image: ${DOCKER_REGISTRY:-docker.elastic.co/elasticsearch}/elasticsearch:8.7.1
    networks:
      backend:

  kibana:
    depends_on:
      - elasticsearch
    image: ${DOCKER_REGISTRY:-docker.elastic.co/kibana}/kibana:8.7.1
    networks:
      backend:
  
  logstash:
    depends_on:
      - elasticsearch
    image: ${DOCKER_REGISTRY:-docker.elastic.co/logstash}/logstash:8.7.1
    networks:
      backend:
