networks:
  backend:
    name: backend
    attachable: true

services:

  text-annotation-api:
    image: ${DOCKER_REGISTRY:-index.docker.io}/drop/services/text-annotation:${TEXT_ANNOTATION_RELEASE:-local}
    networks:
      backend:

  text-geocode-api:
    image: ${DOCKER_REGISTRY:-index.docker.io}/drop/services/text-geocode:${TEXT_GEOCODE_RELEASE:-local}
    networks:
      backend:

  extraction-api:
    depends_on:
      - elasticsearch
    image: ${DOCKER_REGISTRY:-index.docker.io}/drop/services/extraction-api:${EXTRACTION_API_RELEASE:-local}
    networks:
      backend:

  extraction-worker:
    depends_on:
      - elasticsearch
    image: ${DOCKER_REGISTRY:-index.docker.io}/drop/services/extraction-worker:${EXTRACTION_WORKER_RELEASE:-local}
    networks:
      backend:

  elasticsearch:
    image: ${DOCKER_REGISTRY:-docker.elastic.co/elasticsearch}/elasticsearch:${ELASTIC_VERSION:-8.7.1}
    networks:
      backend:

  kibana:
    depends_on:
      - elasticsearch
    image: ${DOCKER_REGISTRY:-docker.elastic.co/kibana}/kibana:${ELASTIC_VERSION:-8.7.1}
    networks:
      backend:
