name: Extractors CI

on:
  push:

jobs:
  extractors-ci:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ["3.10"]

    steps:
      - uses: actions/checkout@v3
      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python-version }}
          cache: 'pip'
      - name: Setup Python Virtual Environment
        run: |
          python -m pip install --upgrade pip
          pip install poetry pylint
      - name: Setup Poetry config
        run: |
          python -m poetry config virtualenvs.in-project true
      - name: Install Extractors Dependencies
        run: |
          python -m poetry install --directory ./pipeline/extractors --only main
      - name: Run Extractors Tests
        run: |
          cd pipeline/extractors
          .venv/bin/python -m pytest --disable-warnings --verbose
